site_name: K's Garage
site_url: https://an-noying.github.io/
repo_url: https://github.com/AN-NOYING/an-noying.github.io
repo_name: 블로그의 소스코드 보기
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: overrides
  font: false
  language: ko
  favicon: assets/favicon.webp
  icon:
    edit: material/pencil 
    view: material/eye
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - toc.follow
    - toc.integrate
    - navigation.footer
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.action.edit
    - content.action.view
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 다크 모드 전환
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 라이트 모드 전환
      primary: custom
      accent: custom

extra:
  analytics:
    provider: google
    property: G-WD2K7BQBQZ
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AN-NOYING
      name: GitHub
    - icon: fontawesome/solid/rss
      link: /feed_rss_created.xml
      name: RSS

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/lazyload.min.js
  - javascripts/scroll-percentage.min.js
  - javascripts/drag-search.min.js
  - javascripts/back2tb.min.js
  - javascripts/improve-seo.min.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - markdown-exec
  - search:
      lang: ko
  - rss:
      match_path: "(programming|reversing|game|how-to-use|review|stat)/posts/.*/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
        datetime_format: "%Y-%m-%dT%H:%M:%S"
        default_timezone: Asia/Seoul
  - blog:
      blog_dir: programming
      post_url_format: "{categories}/{file}"
      archive: false
      categories_allowed:
        - 꿀팁
        - 소프트웨어
        - 자료구조
  - blog:
      blog_dir: reversing
      post_url_format: "{categories}/{file}"
      archive: false
      categories_allowed:
        - 리버싱 핵심원리
  - blog:
      blog_dir: game
      post_url_format: "{categories}/{file}"
      archive: false
      categories_allowed:
        - 치트
  - blog:
      blog_dir: how-to-use
      post_url_format: "{categories}/{file}"
      archive: false
      categories_allowed:
        - 소프트웨어
        - 하드웨어
  - blog:
      blog_dir: review
      post_url_format: "{categories}/{file}"
      archive: false
      categories_allowed:
        - 아르바이트
        - 식품
        - 게임
        - 도서
        - 영화
        - 음악
        - 애니메이션
        - 드라마
        - 전자기기
        - LH
        - 의류
  - blog:
      blog_dir: stat
      post_url_format: "{categories}/{file}"
      archive: false
  - tags

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

nav:
  - HOME: index.md
  - About Me: about.md
  - 리버스 엔지니어링:
    - reversing/index.md
  - 프로그래밍:
    - programming/index.md
  - 게임:
    - game/index.md
  - 사용법:
    - how-to-use/index.md
  - 후기:
    - review/index.md
  - 통계 및 분석:
    - stat/index.md